root: true

env:
  es2021: true
  browser: true

extends:
  - airbnb-base
  - eslint:recommended
  - plugin:react/recommended
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  'import/resolver':
    node: 
      extensions: ['.js', '.jsx']
      moduleDirectory: ['node_modules', 'src/']

plugins:
  - 'react'
  - 'import'
  - prettier

rules:
  no-console: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  no-restricted-exports: off
  no-shadow: off
  react/react-in-jsx-scope: off
  react/prop-types: off